language: python
python:
  - "2.7"
  - "3.7"
install:
  - pip install -r sandbox/requirements.txt
script:
  - python -m pytest tests
# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/
