language: python
python:
  - "2.7"
  - "3.7"
install:
  - pip3 install -r requirements.txt
script:
  - python3 -m pytest tests
# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/
